### ISSUE TITLE
<helmrelease>-db2u-restore-morph-job Errors - The default database not found in system catalog

### ISSUE THREAD

**Issue by hjoshua** [IBM/Db2#27]
```
global:
  dbType: db2wh
images:
  db2u:
    replicas: 1
mln:
  distribution: '2:1'
  total: 2
limit:
  cpu: 5000m 
  memory: 5Gi
storage:
  storageClassName: nfs-client
  useDynamicProvisioning: true
  persisted: true
subType: mpp
dedicated: true
runtime: ICP4Data

```

Using this chart: https://github.com/IBM/Db2/tree/develop/deployment/ibm-db2u

This is our nfs-client storageclass
```Name:                  nfs-client
IsDefaultClass:        No
Annotations:           <none>
Provisioner:           cluster.local/nfs-nfs-client-provisioner
Parameters:            archiveOnDelete=true
AllowVolumeExpansion:  True
MountOptions:
  nfsvers=4
  context=system_u:object_r:container_file_t:s0
ReclaimPolicy:      Delete
VolumeBindingMode:  Immediate
Events:             <none>
```

This happened after we uninstall and re-installed db2 several times. 
Note that we label our nodes with "icp4data=database-db2wh"
